package com.feng.dao;

import com.feng.bean.Company;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CompanyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated
     */
    Company selectByPrimaryKey(CompanyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Company record);
}