server:
  port: 8086
spring:
  application:
    name: company-frame
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.131.168:3306/CLASS?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Dataadt123!

mybatis:
  # 配置映射类所在的包名
  type-aliases-package: com.feng.bean
  # 配置 mapper xml 文件所在的路径， 如果不配置 会报错：org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)
  mapper-locations: classpath:mapper/*.xml