server:
  port: 8083
spring:
  application:
    name: company-frame
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.131.168:3306/COMPANY?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Dataadt123!

mybatis:
  # 配置多个 type-aliases-package
  type-aliases-package: com.feng.bean
  #加入以下配置 对应生成 mapper.xml 的路径
  mapper-locations: classpath:mapper/*.xml