package com.feng.bean;

import java.io.Serializable;
import java.util.Date;

public class Company extends CompanyKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.TYC_ID
     *
     * @mbggenerated
     */
    private Long tycId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COMPANY_NAME
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COMPANY_AIDCODE
     *
     * @mbggenerated
     */
    private String companyAidcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.LEGAL_PERSON_ID
     *
     * @mbggenerated
     */
    private Long legalPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.LEGAL_PERSON_NAME
     *
     * @mbggenerated
     */
    private String legalPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.LEGAL_PERSON_TYPE
     *
     * @mbggenerated
     */
    private Integer legalPersonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.LEGAL_PERSON_SCORE
     *
     * @mbggenerated
     */
    private Integer legalPersonScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.REG_NUMBER
     *
     * @mbggenerated
     */
    private String regNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COMPANY_TYPE
     *
     * @mbggenerated
     */
    private Short companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COMPANY_ORG_TYPE
     *
     * @mbggenerated
     */
    private String companyOrgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COMPANY_TYPE_SCORE
     *
     * @mbggenerated
     */
    private Integer companyTypeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.REG_LOCATION
     *
     * @mbggenerated
     */
    private String regLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.ESTIBLISH_TIME
     *
     * @mbggenerated
     */
    private Date estiblishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.FROM_TIME
     *
     * @mbggenerated
     */
    private Date fromTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.TO_TIME
     *
     * @mbggenerated
     */
    private Date toTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.BUSINESS_SCOPE
     *
     * @mbggenerated
     */
    private String businessScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.REG_INSTITUTE
     *
     * @mbggenerated
     */
    private String regInstitute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.APPROVED_TIME
     *
     * @mbggenerated
     */
    private Date approvedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.REG_STATUS
     *
     * @mbggenerated
     */
    private String regStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.REG_CAPITAL
     *
     * @mbggenerated
     */
    private String regCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.ACTUAL_CAPITAL
     *
     * @mbggenerated
     */
    private String actualCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.ORG_NUMBER
     *
     * @mbggenerated
     */
    private String orgNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.ORG_APPROVED_INSTITUTE
     *
     * @mbggenerated
     */
    private String orgApprovedInstitute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.FLAG
     *
     * @mbggenerated
     */
    private Short flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.PARENT_ID
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.LIST_CODE
     *
     * @mbggenerated
     */
    private String listCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.OWNERSHIP_STAKE
     *
     * @mbggenerated
     */
    private String ownershipStake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.SOURCE_FLAG
     *
     * @mbggenerated
     */
    private Integer sourceFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.NAME_SUFFIX
     *
     * @mbggenerated
     */
    private String nameSuffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.USC_CODE
     *
     * @mbggenerated
     */
    private String uscCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.FORMER_NAME
     *
     * @mbggenerated
     */
    private String formerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COMPANY_ENNAME
     *
     * @mbggenerated
     */
    private String companyEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.NEW_COM_ID
     *
     * @mbggenerated
     */
    private Long newComId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.USE_FLAG
     *
     * @mbggenerated
     */
    private Integer useFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC01
     *
     * @mbggenerated
     */
    private String desc01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC02
     *
     * @mbggenerated
     */
    private String desc02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC03
     *
     * @mbggenerated
     */
    private String desc03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC04
     *
     * @mbggenerated
     */
    private String desc04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC05
     *
     * @mbggenerated
     */
    private String desc05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC06
     *
     * @mbggenerated
     */
    private String desc06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC07
     *
     * @mbggenerated
     */
    private String desc07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC08
     *
     * @mbggenerated
     */
    private String desc08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC09
     *
     * @mbggenerated
     */
    private String desc09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.DESC10
     *
     * @mbggenerated
     */
    private String desc10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.CRAWLED_TIME
     *
     * @mbggenerated
     */
    private Date crawledTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.PUBLISH_TIME
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.URL_LINK
     *
     * @mbggenerated
     */
    private String urlLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COLLECTOR_NAME
     *
     * @mbggenerated
     */
    private String collectorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COLLECT_TIME
     *
     * @mbggenerated
     */
    private Date collectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COLLECT_FLAG
     *
     * @mbggenerated
     */
    private Integer collectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.CLEANER_NAME
     *
     * @mbggenerated
     */
    private String cleanerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.CLEAN_TIME
     *
     * @mbggenerated
     */
    private Date cleanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.CLEAN_FLAG
     *
     * @mbggenerated
     */
    private Integer cleanFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.UPDATE_REASON
     *
     * @mbggenerated
     */
    private String updateReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.TIME_STAMP
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.VERSION_ID
     *
     * @mbggenerated
     */
    private Integer versionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMPANY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.TYC_ID
     *
     * @return the value of COMPANY.TYC_ID
     *
     * @mbggenerated
     */
    public Long getTycId() {
        return tycId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.TYC_ID
     *
     * @param tycId the value for COMPANY.TYC_ID
     *
     * @mbggenerated
     */
    public void setTycId(Long tycId) {
        this.tycId = tycId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COMPANY_NAME
     *
     * @return the value of COMPANY.COMPANY_NAME
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COMPANY_NAME
     *
     * @param companyName the value for COMPANY.COMPANY_NAME
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COMPANY_AIDCODE
     *
     * @return the value of COMPANY.COMPANY_AIDCODE
     *
     * @mbggenerated
     */
    public String getCompanyAidcode() {
        return companyAidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COMPANY_AIDCODE
     *
     * @param companyAidcode the value for COMPANY.COMPANY_AIDCODE
     *
     * @mbggenerated
     */
    public void setCompanyAidcode(String companyAidcode) {
        this.companyAidcode = companyAidcode == null ? null : companyAidcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.LEGAL_PERSON_ID
     *
     * @return the value of COMPANY.LEGAL_PERSON_ID
     *
     * @mbggenerated
     */
    public Long getLegalPersonId() {
        return legalPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.LEGAL_PERSON_ID
     *
     * @param legalPersonId the value for COMPANY.LEGAL_PERSON_ID
     *
     * @mbggenerated
     */
    public void setLegalPersonId(Long legalPersonId) {
        this.legalPersonId = legalPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.LEGAL_PERSON_NAME
     *
     * @return the value of COMPANY.LEGAL_PERSON_NAME
     *
     * @mbggenerated
     */
    public String getLegalPersonName() {
        return legalPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.LEGAL_PERSON_NAME
     *
     * @param legalPersonName the value for COMPANY.LEGAL_PERSON_NAME
     *
     * @mbggenerated
     */
    public void setLegalPersonName(String legalPersonName) {
        this.legalPersonName = legalPersonName == null ? null : legalPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.LEGAL_PERSON_TYPE
     *
     * @return the value of COMPANY.LEGAL_PERSON_TYPE
     *
     * @mbggenerated
     */
    public Integer getLegalPersonType() {
        return legalPersonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.LEGAL_PERSON_TYPE
     *
     * @param legalPersonType the value for COMPANY.LEGAL_PERSON_TYPE
     *
     * @mbggenerated
     */
    public void setLegalPersonType(Integer legalPersonType) {
        this.legalPersonType = legalPersonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.LEGAL_PERSON_SCORE
     *
     * @return the value of COMPANY.LEGAL_PERSON_SCORE
     *
     * @mbggenerated
     */
    public Integer getLegalPersonScore() {
        return legalPersonScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.LEGAL_PERSON_SCORE
     *
     * @param legalPersonScore the value for COMPANY.LEGAL_PERSON_SCORE
     *
     * @mbggenerated
     */
    public void setLegalPersonScore(Integer legalPersonScore) {
        this.legalPersonScore = legalPersonScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.REG_NUMBER
     *
     * @return the value of COMPANY.REG_NUMBER
     *
     * @mbggenerated
     */
    public String getRegNumber() {
        return regNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.REG_NUMBER
     *
     * @param regNumber the value for COMPANY.REG_NUMBER
     *
     * @mbggenerated
     */
    public void setRegNumber(String regNumber) {
        this.regNumber = regNumber == null ? null : regNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COMPANY_TYPE
     *
     * @return the value of COMPANY.COMPANY_TYPE
     *
     * @mbggenerated
     */
    public Short getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COMPANY_TYPE
     *
     * @param companyType the value for COMPANY.COMPANY_TYPE
     *
     * @mbggenerated
     */
    public void setCompanyType(Short companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COMPANY_ORG_TYPE
     *
     * @return the value of COMPANY.COMPANY_ORG_TYPE
     *
     * @mbggenerated
     */
    public String getCompanyOrgType() {
        return companyOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COMPANY_ORG_TYPE
     *
     * @param companyOrgType the value for COMPANY.COMPANY_ORG_TYPE
     *
     * @mbggenerated
     */
    public void setCompanyOrgType(String companyOrgType) {
        this.companyOrgType = companyOrgType == null ? null : companyOrgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COMPANY_TYPE_SCORE
     *
     * @return the value of COMPANY.COMPANY_TYPE_SCORE
     *
     * @mbggenerated
     */
    public Integer getCompanyTypeScore() {
        return companyTypeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COMPANY_TYPE_SCORE
     *
     * @param companyTypeScore the value for COMPANY.COMPANY_TYPE_SCORE
     *
     * @mbggenerated
     */
    public void setCompanyTypeScore(Integer companyTypeScore) {
        this.companyTypeScore = companyTypeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.REG_LOCATION
     *
     * @return the value of COMPANY.REG_LOCATION
     *
     * @mbggenerated
     */
    public String getRegLocation() {
        return regLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.REG_LOCATION
     *
     * @param regLocation the value for COMPANY.REG_LOCATION
     *
     * @mbggenerated
     */
    public void setRegLocation(String regLocation) {
        this.regLocation = regLocation == null ? null : regLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.ESTIBLISH_TIME
     *
     * @return the value of COMPANY.ESTIBLISH_TIME
     *
     * @mbggenerated
     */
    public Date getEstiblishTime() {
        return estiblishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.ESTIBLISH_TIME
     *
     * @param estiblishTime the value for COMPANY.ESTIBLISH_TIME
     *
     * @mbggenerated
     */
    public void setEstiblishTime(Date estiblishTime) {
        this.estiblishTime = estiblishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.FROM_TIME
     *
     * @return the value of COMPANY.FROM_TIME
     *
     * @mbggenerated
     */
    public Date getFromTime() {
        return fromTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.FROM_TIME
     *
     * @param fromTime the value for COMPANY.FROM_TIME
     *
     * @mbggenerated
     */
    public void setFromTime(Date fromTime) {
        this.fromTime = fromTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.TO_TIME
     *
     * @return the value of COMPANY.TO_TIME
     *
     * @mbggenerated
     */
    public Date getToTime() {
        return toTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.TO_TIME
     *
     * @param toTime the value for COMPANY.TO_TIME
     *
     * @mbggenerated
     */
    public void setToTime(Date toTime) {
        this.toTime = toTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.BUSINESS_SCOPE
     *
     * @return the value of COMPANY.BUSINESS_SCOPE
     *
     * @mbggenerated
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.BUSINESS_SCOPE
     *
     * @param businessScope the value for COMPANY.BUSINESS_SCOPE
     *
     * @mbggenerated
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.REG_INSTITUTE
     *
     * @return the value of COMPANY.REG_INSTITUTE
     *
     * @mbggenerated
     */
    public String getRegInstitute() {
        return regInstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.REG_INSTITUTE
     *
     * @param regInstitute the value for COMPANY.REG_INSTITUTE
     *
     * @mbggenerated
     */
    public void setRegInstitute(String regInstitute) {
        this.regInstitute = regInstitute == null ? null : regInstitute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.APPROVED_TIME
     *
     * @return the value of COMPANY.APPROVED_TIME
     *
     * @mbggenerated
     */
    public Date getApprovedTime() {
        return approvedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.APPROVED_TIME
     *
     * @param approvedTime the value for COMPANY.APPROVED_TIME
     *
     * @mbggenerated
     */
    public void setApprovedTime(Date approvedTime) {
        this.approvedTime = approvedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.REG_STATUS
     *
     * @return the value of COMPANY.REG_STATUS
     *
     * @mbggenerated
     */
    public String getRegStatus() {
        return regStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.REG_STATUS
     *
     * @param regStatus the value for COMPANY.REG_STATUS
     *
     * @mbggenerated
     */
    public void setRegStatus(String regStatus) {
        this.regStatus = regStatus == null ? null : regStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.REG_CAPITAL
     *
     * @return the value of COMPANY.REG_CAPITAL
     *
     * @mbggenerated
     */
    public String getRegCapital() {
        return regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.REG_CAPITAL
     *
     * @param regCapital the value for COMPANY.REG_CAPITAL
     *
     * @mbggenerated
     */
    public void setRegCapital(String regCapital) {
        this.regCapital = regCapital == null ? null : regCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.ACTUAL_CAPITAL
     *
     * @return the value of COMPANY.ACTUAL_CAPITAL
     *
     * @mbggenerated
     */
    public String getActualCapital() {
        return actualCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.ACTUAL_CAPITAL
     *
     * @param actualCapital the value for COMPANY.ACTUAL_CAPITAL
     *
     * @mbggenerated
     */
    public void setActualCapital(String actualCapital) {
        this.actualCapital = actualCapital == null ? null : actualCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.ORG_NUMBER
     *
     * @return the value of COMPANY.ORG_NUMBER
     *
     * @mbggenerated
     */
    public String getOrgNumber() {
        return orgNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.ORG_NUMBER
     *
     * @param orgNumber the value for COMPANY.ORG_NUMBER
     *
     * @mbggenerated
     */
    public void setOrgNumber(String orgNumber) {
        this.orgNumber = orgNumber == null ? null : orgNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.ORG_APPROVED_INSTITUTE
     *
     * @return the value of COMPANY.ORG_APPROVED_INSTITUTE
     *
     * @mbggenerated
     */
    public String getOrgApprovedInstitute() {
        return orgApprovedInstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.ORG_APPROVED_INSTITUTE
     *
     * @param orgApprovedInstitute the value for COMPANY.ORG_APPROVED_INSTITUTE
     *
     * @mbggenerated
     */
    public void setOrgApprovedInstitute(String orgApprovedInstitute) {
        this.orgApprovedInstitute = orgApprovedInstitute == null ? null : orgApprovedInstitute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.FLAG
     *
     * @return the value of COMPANY.FLAG
     *
     * @mbggenerated
     */
    public Short getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.FLAG
     *
     * @param flag the value for COMPANY.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(Short flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.PARENT_ID
     *
     * @return the value of COMPANY.PARENT_ID
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.PARENT_ID
     *
     * @param parentId the value for COMPANY.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.UPDATE_DATE
     *
     * @return the value of COMPANY.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.UPDATE_DATE
     *
     * @param updateDate the value for COMPANY.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.LIST_CODE
     *
     * @return the value of COMPANY.LIST_CODE
     *
     * @mbggenerated
     */
    public String getListCode() {
        return listCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.LIST_CODE
     *
     * @param listCode the value for COMPANY.LIST_CODE
     *
     * @mbggenerated
     */
    public void setListCode(String listCode) {
        this.listCode = listCode == null ? null : listCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.OWNERSHIP_STAKE
     *
     * @return the value of COMPANY.OWNERSHIP_STAKE
     *
     * @mbggenerated
     */
    public String getOwnershipStake() {
        return ownershipStake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.OWNERSHIP_STAKE
     *
     * @param ownershipStake the value for COMPANY.OWNERSHIP_STAKE
     *
     * @mbggenerated
     */
    public void setOwnershipStake(String ownershipStake) {
        this.ownershipStake = ownershipStake == null ? null : ownershipStake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.SOURCE_FLAG
     *
     * @return the value of COMPANY.SOURCE_FLAG
     *
     * @mbggenerated
     */
    public Integer getSourceFlag() {
        return sourceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.SOURCE_FLAG
     *
     * @param sourceFlag the value for COMPANY.SOURCE_FLAG
     *
     * @mbggenerated
     */
    public void setSourceFlag(Integer sourceFlag) {
        this.sourceFlag = sourceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.NAME_SUFFIX
     *
     * @return the value of COMPANY.NAME_SUFFIX
     *
     * @mbggenerated
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.NAME_SUFFIX
     *
     * @param nameSuffix the value for COMPANY.NAME_SUFFIX
     *
     * @mbggenerated
     */
    public void setNameSuffix(String nameSuffix) {
        this.nameSuffix = nameSuffix == null ? null : nameSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.USC_CODE
     *
     * @return the value of COMPANY.USC_CODE
     *
     * @mbggenerated
     */
    public String getUscCode() {
        return uscCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.USC_CODE
     *
     * @param uscCode the value for COMPANY.USC_CODE
     *
     * @mbggenerated
     */
    public void setUscCode(String uscCode) {
        this.uscCode = uscCode == null ? null : uscCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.FORMER_NAME
     *
     * @return the value of COMPANY.FORMER_NAME
     *
     * @mbggenerated
     */
    public String getFormerName() {
        return formerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.FORMER_NAME
     *
     * @param formerName the value for COMPANY.FORMER_NAME
     *
     * @mbggenerated
     */
    public void setFormerName(String formerName) {
        this.formerName = formerName == null ? null : formerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COMPANY_ENNAME
     *
     * @return the value of COMPANY.COMPANY_ENNAME
     *
     * @mbggenerated
     */
    public String getCompanyEnname() {
        return companyEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COMPANY_ENNAME
     *
     * @param companyEnname the value for COMPANY.COMPANY_ENNAME
     *
     * @mbggenerated
     */
    public void setCompanyEnname(String companyEnname) {
        this.companyEnname = companyEnname == null ? null : companyEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.NEW_COM_ID
     *
     * @return the value of COMPANY.NEW_COM_ID
     *
     * @mbggenerated
     */
    public Long getNewComId() {
        return newComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.NEW_COM_ID
     *
     * @param newComId the value for COMPANY.NEW_COM_ID
     *
     * @mbggenerated
     */
    public void setNewComId(Long newComId) {
        this.newComId = newComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.USE_FLAG
     *
     * @return the value of COMPANY.USE_FLAG
     *
     * @mbggenerated
     */
    public Integer getUseFlag() {
        return useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.USE_FLAG
     *
     * @param useFlag the value for COMPANY.USE_FLAG
     *
     * @mbggenerated
     */
    public void setUseFlag(Integer useFlag) {
        this.useFlag = useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC01
     *
     * @return the value of COMPANY.DESC01
     *
     * @mbggenerated
     */
    public String getDesc01() {
        return desc01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC01
     *
     * @param desc01 the value for COMPANY.DESC01
     *
     * @mbggenerated
     */
    public void setDesc01(String desc01) {
        this.desc01 = desc01 == null ? null : desc01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC02
     *
     * @return the value of COMPANY.DESC02
     *
     * @mbggenerated
     */
    public String getDesc02() {
        return desc02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC02
     *
     * @param desc02 the value for COMPANY.DESC02
     *
     * @mbggenerated
     */
    public void setDesc02(String desc02) {
        this.desc02 = desc02 == null ? null : desc02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC03
     *
     * @return the value of COMPANY.DESC03
     *
     * @mbggenerated
     */
    public String getDesc03() {
        return desc03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC03
     *
     * @param desc03 the value for COMPANY.DESC03
     *
     * @mbggenerated
     */
    public void setDesc03(String desc03) {
        this.desc03 = desc03 == null ? null : desc03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC04
     *
     * @return the value of COMPANY.DESC04
     *
     * @mbggenerated
     */
    public String getDesc04() {
        return desc04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC04
     *
     * @param desc04 the value for COMPANY.DESC04
     *
     * @mbggenerated
     */
    public void setDesc04(String desc04) {
        this.desc04 = desc04 == null ? null : desc04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC05
     *
     * @return the value of COMPANY.DESC05
     *
     * @mbggenerated
     */
    public String getDesc05() {
        return desc05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC05
     *
     * @param desc05 the value for COMPANY.DESC05
     *
     * @mbggenerated
     */
    public void setDesc05(String desc05) {
        this.desc05 = desc05 == null ? null : desc05.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC06
     *
     * @return the value of COMPANY.DESC06
     *
     * @mbggenerated
     */
    public String getDesc06() {
        return desc06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC06
     *
     * @param desc06 the value for COMPANY.DESC06
     *
     * @mbggenerated
     */
    public void setDesc06(String desc06) {
        this.desc06 = desc06 == null ? null : desc06.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC07
     *
     * @return the value of COMPANY.DESC07
     *
     * @mbggenerated
     */
    public String getDesc07() {
        return desc07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC07
     *
     * @param desc07 the value for COMPANY.DESC07
     *
     * @mbggenerated
     */
    public void setDesc07(String desc07) {
        this.desc07 = desc07 == null ? null : desc07.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC08
     *
     * @return the value of COMPANY.DESC08
     *
     * @mbggenerated
     */
    public String getDesc08() {
        return desc08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC08
     *
     * @param desc08 the value for COMPANY.DESC08
     *
     * @mbggenerated
     */
    public void setDesc08(String desc08) {
        this.desc08 = desc08 == null ? null : desc08.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC09
     *
     * @return the value of COMPANY.DESC09
     *
     * @mbggenerated
     */
    public String getDesc09() {
        return desc09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC09
     *
     * @param desc09 the value for COMPANY.DESC09
     *
     * @mbggenerated
     */
    public void setDesc09(String desc09) {
        this.desc09 = desc09 == null ? null : desc09.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.DESC10
     *
     * @return the value of COMPANY.DESC10
     *
     * @mbggenerated
     */
    public String getDesc10() {
        return desc10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.DESC10
     *
     * @param desc10 the value for COMPANY.DESC10
     *
     * @mbggenerated
     */
    public void setDesc10(String desc10) {
        this.desc10 = desc10 == null ? null : desc10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.CRAWLED_TIME
     *
     * @return the value of COMPANY.CRAWLED_TIME
     *
     * @mbggenerated
     */
    public Date getCrawledTime() {
        return crawledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.CRAWLED_TIME
     *
     * @param crawledTime the value for COMPANY.CRAWLED_TIME
     *
     * @mbggenerated
     */
    public void setCrawledTime(Date crawledTime) {
        this.crawledTime = crawledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.PUBLISH_TIME
     *
     * @return the value of COMPANY.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.PUBLISH_TIME
     *
     * @param publishTime the value for COMPANY.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.URL_LINK
     *
     * @return the value of COMPANY.URL_LINK
     *
     * @mbggenerated
     */
    public String getUrlLink() {
        return urlLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.URL_LINK
     *
     * @param urlLink the value for COMPANY.URL_LINK
     *
     * @mbggenerated
     */
    public void setUrlLink(String urlLink) {
        this.urlLink = urlLink == null ? null : urlLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COLLECTOR_NAME
     *
     * @return the value of COMPANY.COLLECTOR_NAME
     *
     * @mbggenerated
     */
    public String getCollectorName() {
        return collectorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COLLECTOR_NAME
     *
     * @param collectorName the value for COMPANY.COLLECTOR_NAME
     *
     * @mbggenerated
     */
    public void setCollectorName(String collectorName) {
        this.collectorName = collectorName == null ? null : collectorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COLLECT_TIME
     *
     * @return the value of COMPANY.COLLECT_TIME
     *
     * @mbggenerated
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COLLECT_TIME
     *
     * @param collectTime the value for COMPANY.COLLECT_TIME
     *
     * @mbggenerated
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COLLECT_FLAG
     *
     * @return the value of COMPANY.COLLECT_FLAG
     *
     * @mbggenerated
     */
    public Integer getCollectFlag() {
        return collectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COLLECT_FLAG
     *
     * @param collectFlag the value for COMPANY.COLLECT_FLAG
     *
     * @mbggenerated
     */
    public void setCollectFlag(Integer collectFlag) {
        this.collectFlag = collectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.CLEANER_NAME
     *
     * @return the value of COMPANY.CLEANER_NAME
     *
     * @mbggenerated
     */
    public String getCleanerName() {
        return cleanerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.CLEANER_NAME
     *
     * @param cleanerName the value for COMPANY.CLEANER_NAME
     *
     * @mbggenerated
     */
    public void setCleanerName(String cleanerName) {
        this.cleanerName = cleanerName == null ? null : cleanerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.CLEAN_TIME
     *
     * @return the value of COMPANY.CLEAN_TIME
     *
     * @mbggenerated
     */
    public Date getCleanTime() {
        return cleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.CLEAN_TIME
     *
     * @param cleanTime the value for COMPANY.CLEAN_TIME
     *
     * @mbggenerated
     */
    public void setCleanTime(Date cleanTime) {
        this.cleanTime = cleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.CLEAN_FLAG
     *
     * @return the value of COMPANY.CLEAN_FLAG
     *
     * @mbggenerated
     */
    public Integer getCleanFlag() {
        return cleanFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.CLEAN_FLAG
     *
     * @param cleanFlag the value for COMPANY.CLEAN_FLAG
     *
     * @mbggenerated
     */
    public void setCleanFlag(Integer cleanFlag) {
        this.cleanFlag = cleanFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.UPDATE_REASON
     *
     * @return the value of COMPANY.UPDATE_REASON
     *
     * @mbggenerated
     */
    public String getUpdateReason() {
        return updateReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.UPDATE_REASON
     *
     * @param updateReason the value for COMPANY.UPDATE_REASON
     *
     * @mbggenerated
     */
    public void setUpdateReason(String updateReason) {
        this.updateReason = updateReason == null ? null : updateReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.TIME_STAMP
     *
     * @return the value of COMPANY.TIME_STAMP
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.TIME_STAMP
     *
     * @param timeStamp the value for COMPANY.TIME_STAMP
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.VERSION_ID
     *
     * @return the value of COMPANY.VERSION_ID
     *
     * @mbggenerated
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.VERSION_ID
     *
     * @param versionId the value for COMPANY.VERSION_ID
     *
     * @mbggenerated
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tycId=").append(tycId);
        sb.append(", companyName=").append(companyName);
        sb.append(", companyAidcode=").append(companyAidcode);
        sb.append(", legalPersonId=").append(legalPersonId);
        sb.append(", legalPersonName=").append(legalPersonName);
        sb.append(", legalPersonType=").append(legalPersonType);
        sb.append(", legalPersonScore=").append(legalPersonScore);
        sb.append(", regNumber=").append(regNumber);
        sb.append(", companyType=").append(companyType);
        sb.append(", companyOrgType=").append(companyOrgType);
        sb.append(", companyTypeScore=").append(companyTypeScore);
        sb.append(", regLocation=").append(regLocation);
        sb.append(", estiblishTime=").append(estiblishTime);
        sb.append(", fromTime=").append(fromTime);
        sb.append(", toTime=").append(toTime);
        sb.append(", businessScope=").append(businessScope);
        sb.append(", regInstitute=").append(regInstitute);
        sb.append(", approvedTime=").append(approvedTime);
        sb.append(", regStatus=").append(regStatus);
        sb.append(", regCapital=").append(regCapital);
        sb.append(", actualCapital=").append(actualCapital);
        sb.append(", orgNumber=").append(orgNumber);
        sb.append(", orgApprovedInstitute=").append(orgApprovedInstitute);
        sb.append(", flag=").append(flag);
        sb.append(", parentId=").append(parentId);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", listCode=").append(listCode);
        sb.append(", ownershipStake=").append(ownershipStake);
        sb.append(", sourceFlag=").append(sourceFlag);
        sb.append(", nameSuffix=").append(nameSuffix);
        sb.append(", uscCode=").append(uscCode);
        sb.append(", formerName=").append(formerName);
        sb.append(", companyEnname=").append(companyEnname);
        sb.append(", newComId=").append(newComId);
        sb.append(", useFlag=").append(useFlag);
        sb.append(", desc01=").append(desc01);
        sb.append(", desc02=").append(desc02);
        sb.append(", desc03=").append(desc03);
        sb.append(", desc04=").append(desc04);
        sb.append(", desc05=").append(desc05);
        sb.append(", desc06=").append(desc06);
        sb.append(", desc07=").append(desc07);
        sb.append(", desc08=").append(desc08);
        sb.append(", desc09=").append(desc09);
        sb.append(", desc10=").append(desc10);
        sb.append(", crawledTime=").append(crawledTime);
        sb.append(", publishTime=").append(publishTime);
        sb.append(", urlLink=").append(urlLink);
        sb.append(", collectorName=").append(collectorName);
        sb.append(", collectTime=").append(collectTime);
        sb.append(", collectFlag=").append(collectFlag);
        sb.append(", cleanerName=").append(cleanerName);
        sb.append(", cleanTime=").append(cleanTime);
        sb.append(", cleanFlag=").append(cleanFlag);
        sb.append(", updateReason=").append(updateReason);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", versionId=").append(versionId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}